### ISSUE TITLE
[Featrue] 동영상 재생

### ISSUE THREAD

**Issue by younghyun-j** [younghyun-j/streaming-service#2]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
- 등록된 동영상을 재생하는 기능을 구현합니다.
- 등록된 동영상은 외부 저장소에 있어, 동영상이 저장된 URL과 필요한 정보를 응답합니다.

## ✅ TODO
- [ ] 동영상 재생 API
- [ ] 재생 시 기존에 조회했던 영상의 경우 최근 재생 시점부터 재생되고, 최초 조회의 경우 처음부터 조회 됩니다. 
- [ ] 재생 시 해당 영상의 조회수가 증가 합니다.
- [ ] 중단 시 현재까지 재생한 시점이 저장됩니다.

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
